package com.code.entity;

import java.util.Date;

public class Coordinates {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coordinates.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coordinates.geoType
     *
     * @mbg.generated
     */
    private String geotype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coordinates.entryTime
     *
     * @mbg.generated
     */
    private Date entrytime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coordinates.modifyTime
     *
     * @mbg.generated
     */
    private Date modifytime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coordinates.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coordinates.geo
     * 空间字段直接转为String来存储读取
     * @mbg.generated
     */
    private String geo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coordinates.id
     *
     * @return the value of coordinates.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coordinates.id
     *
     * @param id the value for coordinates.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coordinates.geoType
     *
     * @return the value of coordinates.geoType
     *
     * @mbg.generated
     */
    public String getGeotype() {
        return geotype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coordinates.geoType
     *
     * @param geotype the value for coordinates.geoType
     *
     * @mbg.generated
     */
    public void setGeotype(String geotype) {
        this.geotype = geotype == null ? null : geotype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coordinates.entryTime
     *
     * @return the value of coordinates.entryTime
     *
     * @mbg.generated
     */
    public Date getEntrytime() {
        return entrytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coordinates.entryTime
     *
     * @param entrytime the value for coordinates.entryTime
     *
     * @mbg.generated
     */
    public void setEntrytime(Date entrytime) {
        this.entrytime = entrytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coordinates.modifyTime
     *
     * @return the value of coordinates.modifyTime
     *
     * @mbg.generated
     */
    public Date getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coordinates.modifyTime
     *
     * @param modifytime the value for coordinates.modifyTime
     *
     * @mbg.generated
     */
    public void setModifytime(Date modifytime) {
        this.modifytime = modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coordinates.remark
     *
     * @return the value of coordinates.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coordinates.remark
     *
     * @param remark the value for coordinates.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coordinates.geo
     *
     * @return the value of coordinates.geo
     *
     * @mbg.generated
     */
    public String getGeo() {
        return geo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coordinates.geo
     *
     * @param geo the value for coordinates.geo
     *
     * @mbg.generated
     */
    public void setGeo(String geo) {
        this.geo = geo;
    }
}