package com.code.entity;

import java.util.Date;

public class Uploadfile {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uploadfile.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uploadfile.fileName
     *
     * @mbg.generated
     */
    private String filename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uploadfile.fileUrl
     *
     * @mbg.generated
     */
    private String fileurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uploadfile.fileUrlManage
     *
     * @mbg.generated
     */
    private String fileurlmanage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uploadfile.uploadTime
     *
     * @mbg.generated
     */
    private Date uploadtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uploadfile.uploadUser
     *
     * @mbg.generated
     */
    private String uploaduser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uploadfile.fileType
     *
     * @mbg.generated
     */
    private String filetype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uploadfile.fileStatus
     *
     * @mbg.generated
     */
    private Integer filestatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uploadfile.relateTable
     *
     * @mbg.generated
     */
    private String relatetable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uploadfile.relateId
     *
     * @mbg.generated
     */
    private String relateid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uploadfile.id
     *
     * @return the value of uploadfile.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uploadfile.id
     *
     * @param id the value for uploadfile.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uploadfile.fileName
     *
     * @return the value of uploadfile.fileName
     *
     * @mbg.generated
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uploadfile.fileName
     *
     * @param filename the value for uploadfile.fileName
     *
     * @mbg.generated
     */
    public void setFilename(String filename) {
        this.filename = filename == null ? null : filename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uploadfile.fileUrl
     *
     * @return the value of uploadfile.fileUrl
     *
     * @mbg.generated
     */
    public String getFileurl() {
        return fileurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uploadfile.fileUrl
     *
     * @param fileurl the value for uploadfile.fileUrl
     *
     * @mbg.generated
     */
    public void setFileurl(String fileurl) {
        this.fileurl = fileurl == null ? null : fileurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uploadfile.fileUrlManage
     *
     * @return the value of uploadfile.fileUrlManage
     *
     * @mbg.generated
     */
    public String getFileurlmanage() {
        return fileurlmanage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uploadfile.fileUrlManage
     *
     * @param fileurlmanage the value for uploadfile.fileUrlManage
     *
     * @mbg.generated
     */
    public void setFileurlmanage(String fileurlmanage) {
        this.fileurlmanage = fileurlmanage == null ? null : fileurlmanage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uploadfile.uploadTime
     *
     * @return the value of uploadfile.uploadTime
     *
     * @mbg.generated
     */
    public Date getUploadtime() {
        return uploadtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uploadfile.uploadTime
     *
     * @param uploadtime the value for uploadfile.uploadTime
     *
     * @mbg.generated
     */
    public void setUploadtime(Date uploadtime) {
        this.uploadtime = uploadtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uploadfile.uploadUser
     *
     * @return the value of uploadfile.uploadUser
     *
     * @mbg.generated
     */
    public String getUploaduser() {
        return uploaduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uploadfile.uploadUser
     *
     * @param uploaduser the value for uploadfile.uploadUser
     *
     * @mbg.generated
     */
    public void setUploaduser(String uploaduser) {
        this.uploaduser = uploaduser == null ? null : uploaduser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uploadfile.fileType
     *
     * @return the value of uploadfile.fileType
     *
     * @mbg.generated
     */
    public String getFiletype() {
        return filetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uploadfile.fileType
     *
     * @param filetype the value for uploadfile.fileType
     *
     * @mbg.generated
     */
    public void setFiletype(String filetype) {
        this.filetype = filetype == null ? null : filetype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uploadfile.fileStatus
     *
     * @return the value of uploadfile.fileStatus
     *
     * @mbg.generated
     */
    public Integer getFilestatus() {
        return filestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uploadfile.fileStatus
     *
     * @param filestatus the value for uploadfile.fileStatus
     *
     * @mbg.generated
     */
    public void setFilestatus(Integer filestatus) {
        this.filestatus = filestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uploadfile.relateTable
     *
     * @return the value of uploadfile.relateTable
     *
     * @mbg.generated
     */
    public String getRelatetable() {
        return relatetable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uploadfile.relateTable
     *
     * @param relatetable the value for uploadfile.relateTable
     *
     * @mbg.generated
     */
    public void setRelatetable(String relatetable) {
        this.relatetable = relatetable == null ? null : relatetable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uploadfile.relateId
     *
     * @return the value of uploadfile.relateId
     *
     * @mbg.generated
     */
    public String getRelateid() {
        return relateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uploadfile.relateId
     *
     * @param relateid the value for uploadfile.relateId
     *
     * @mbg.generated
     */
    public void setRelateid(String relateid) {
        this.relateid = relateid == null ? null : relateid.trim();
    }
}