package com.code.dao;

import com.code.entity.Coordinates;

public interface CoordinatesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coordinates
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coordinates
     *
     * @mbg.generated
     */
    int insert(Coordinates record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coordinates
     *
     * @mbg.generated
     */
    int insertSelective(Coordinates record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coordinates
     *
     * @mbg.generated
     */
    Coordinates selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coordinates
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Coordinates record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coordinates
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(Coordinates record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coordinates
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Coordinates record);
}